# ===== TELEGRAM =====
TELEGRAM_TOKEN = "YOUR_TELEGRAM_BOT_TOKEN"
CHAT_ID = "YOUR_CHAT_ID"

# ===== STRATEGY =====
TIMEFRAME = "5m"
EMA_LENGTH = 34
RR_RATIO = 2.0

# ===== BOT =====
SCAN_INTERVAL = 60          # seconds
HEARTBEAT_INTERVAL = 900    # 15 minutes
MAX_COINS = 50
